// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: attributes/v1/attributes.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttributeInstance is created by selecting the Authority, Name and a specific Value from
// an AttributeDefinition.
//
// An AttributeInstance is a single, unique attribute, with a single value.
//
// Applied to an entity, the AttributeInstance becomes an entity attribute.
// Applied to data, the AttributeInstance becomes a data attribute.
//
// When making an access decisions, these two kinds of AttributeInstances are compared with each other.
//
// Example AttributeInstance:
// https://derp.com/attr/Blob/value/Green ->
//  Authority = https://derp.com
//  Name = Blob
//  CanonicalName = Authority + Name https://derp.com/attr/Blob
//  Value = Green
type AttributeInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AttributeInstance) Reset() {
	*x = AttributeInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_v1_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeInstance) ProtoMessage() {}

func (x *AttributeInstance) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_v1_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeInstance.ProtoReflect.Descriptor instead.
func (*AttributeInstance) Descriptor() ([]byte, []int) {
	return file_attributes_v1_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeInstance) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *AttributeInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeInstance) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// AttributeDefinition describes metadata about the attribute -
// it's name, it's authority, it's rule, it's valid values, etc.
//
// Instances, not Definitions, are compared for access decisions.
//
// An AttributeDefinition is not "an attribute" and cannot be used for access decisions,
// it simply described how a given AttributeInstance should be compared.
//
// Every Instance has a parent Definition, but not every Definition has an Instance.
type AttributeDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authority string             `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Name      string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rule      string             `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	State     *string            `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
	GroupBy   *AttributeInstance `protobuf:"bytes,5,opt,name=group_by,json=groupBy,proto3,oneof" json:"group_by,omitempty"`
	//'order' contains all the valid values an Instance of this Definition may
	//have. If the `rule` is == hierarchy, then the ordering of these values implies
	//their hierarchical position.
	Order []string `protobuf:"bytes,6,rep,name=order,proto3" json:"order,omitempty"`
}

func (x *AttributeDefinition) Reset() {
	*x = AttributeDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_v1_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDefinition) ProtoMessage() {}

func (x *AttributeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_v1_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDefinition.ProtoReflect.Descriptor instead.
func (*AttributeDefinition) Descriptor() ([]byte, []int) {
	return file_attributes_v1_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeDefinition) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *AttributeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeDefinition) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *AttributeDefinition) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *AttributeDefinition) GetGroupBy() *AttributeInstance {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *AttributeDefinition) GetOrder() []string {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_attributes_v1_attributes_proto protoreflect.FileDescriptor

var file_attributes_v1_attributes_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22,
	0x5b, 0x0a, 0x11, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xe5, 0x01, 0x0a,
	0x13, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x40, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x62,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x48, 0x01, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x42, 0x79, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x62, 0x79, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x72, 0x75, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x2d, 0x70, 0x64, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_attributes_v1_attributes_proto_rawDescOnce sync.Once
	file_attributes_v1_attributes_proto_rawDescData = file_attributes_v1_attributes_proto_rawDesc
)

func file_attributes_v1_attributes_proto_rawDescGZIP() []byte {
	file_attributes_v1_attributes_proto_rawDescOnce.Do(func() {
		file_attributes_v1_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_attributes_v1_attributes_proto_rawDescData)
	})
	return file_attributes_v1_attributes_proto_rawDescData
}

var file_attributes_v1_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_attributes_v1_attributes_proto_goTypes = []interface{}{
	(*AttributeInstance)(nil),   // 0: attributes.v1.AttributeInstance
	(*AttributeDefinition)(nil), // 1: attributes.v1.AttributeDefinition
}
var file_attributes_v1_attributes_proto_depIdxs = []int32{
	0, // 0: attributes.v1.AttributeDefinition.group_by:type_name -> attributes.v1.AttributeInstance
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_attributes_v1_attributes_proto_init() }
func file_attributes_v1_attributes_proto_init() {
	if File_attributes_v1_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_attributes_v1_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attributes_v1_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_attributes_v1_attributes_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_attributes_v1_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attributes_v1_attributes_proto_goTypes,
		DependencyIndexes: file_attributes_v1_attributes_proto_depIdxs,
		MessageInfos:      file_attributes_v1_attributes_proto_msgTypes,
	}.Build()
	File_attributes_v1_attributes_proto = out.File
	file_attributes_v1_attributes_proto_rawDesc = nil
	file_attributes_v1_attributes_proto_goTypes = nil
	file_attributes_v1_attributes_proto_depIdxs = nil
}
